# src/latest_ai_development/config/tasks.yaml

research_task:
  description: >
    Conduct a thorough research about {topic}.
    Make sure you find any interesting and relevant information given
    the current year is 2025.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}.
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information,
    formatted as markdown (without the triple backticks).
  agent: reporting_analyst
  output_file: report.md

crew_management_task:
  description: >
    Coordinate and oversee development tasks among all agents. Draft an action plan
    detailing which agent works on what, setting milestones and deadlines.
  expected_output: >
    A structured plan (in bullet points) mapping tasks to each agent, including timelines
    and critical objectives for the overall multi-agent development cycle.
  agent: crew_captain

architecture_planning_task:
  description: >
    Design or refine a high-level software architecture and ensure the project's technical
    vision remains coherent. Identify the major system components, their interactions,
    and any potential scalability or security concerns.
  expected_output: >
    An architectural overview (as bullet points or diagrams described in text) including
    rationale for key design decisions.
  agent: system_architect

frontend_implementation_task:
  description: >
    Implement the front-end components based on the provided UI/UX designs and guidelines.
    Ensure responsiveness, accessibility, and maintainability.
  expected_output: >
    A set of well-structured front-end files (HTML, CSS, JS or framework-specific equivalents)
    and a short summary of implementation details.
  agent: frontend_developer

backend_development_task:
  description: >
    Implement the server-side logic and APIs, integrate with databases, and ensure
    data models are well-structured and secure.
  expected_output: >
    An outline of the API endpoints, the data models used, and any relevant code snippets
    demonstrating completed backend functionality.
  agent: backend_developer

devops_pipeline_task:
  description: >
    Set up or refine the continuous integration and deployment (CI/CD) pipelines, environment
    configurations, and monitoring solutions.
  expected_output: >
    A brief summary of pipeline configurations, environment setup scripts, or infrastructure
    as code, and instructions for running or deploying the system.
  agent: devops_engineer

quality_assurance_task:
  description: >
    Design and run test suites, including unit, integration, and end-to-end tests. Document
    any bugs or issues found, along with steps to reproduce them.
  expected_output: >
    A test report containing test coverage summaries, a list of bugs (if any), and suggestions
    for improvements to increase code reliability.
  agent: qa_specialist

code_review_task:
  description: >
    Review the latest pull requests and commit history for the codebase. Identify any issues
    with standards, performance, readability, or design. Suggest improvements.
  expected_output: >
    A set of code review notes for each pull request, detailing potential problems and areas
    for refactoring, along with concise recommendations.
  agent: code_reviewer